openapi: "3.0.0"
info:
  title: Api
  description: Patient Api
  version: 1.0.0

servers:
  - url: http://api.example.com/v1
    description: Main (production) server

paths:
  /patients:
    post:
      summary: Create new Patient.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatientDetails'
      responses:
        '201':
          description: Return succes created message
          content:
            application/json:
              schema:
                  type: string
    get:
      summary: Get all patients
      responses:
        '200':
          description: List of patient object.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PatientDetails'
        '404':
          description: Return not found message
          content:
            application/json:
              schema:
                type: string
  /patients/{secNumber}:
    get:
      summary: Returns a patient by secNumber.
      parameters:
        - name: secNumber
          in: path
          required: true
          description: The secNumber of the patient to return.
          schema:
            type: string
      responses:
        '200':
          description: A patient object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatientDetails'
        '400':
          description: Return bad request message
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Return not found message
          content:
            application/json:
              schema:
                type: string
    put:
      summary: Update patient by secNumber.
      parameters:
        - name: secNumber
          in: path
          required: true
          description: The secNumber of the patient to return.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatientDetails'
      responses:
        '200':
          description: Updated patient object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatientDetails'
        '400':
          description: Return bad request message
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Return not found message
          content:
            application/json:
              schema:
                type: string
  /patients/{secNumber}/examinations:
    post:
      summary: Create patient examination by secNumber.
      parameters:
        - name: secNumber
          in: path
          required: true
          description: The secNumber of the patient to return.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Examination'
      responses:
        '201':
          description: Succes examination crate message
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Return bad request message
          content:
            application/json:
              schema:
                type: string
    get:
      summary: Get patient examinations by secNumber
      parameters:
        - name: secNumber
          in: path
          required: true
          description: The secNumber of the patient to return.
          schema:
            type: string
      responses:
        '200':
          description: List of examination object.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Examination'
        '404':
          description: Return not found message
          content:
            application/json:
              schema:
                type: string

  /patients/{secNumber}/examinations/{eye}:
    put:
      summary: Update patient examination by secNumber and eyeside composite key.
      parameters:
        - name: secNumber
          in: path
          required: true
          description: The secNumber of the patient to return.
          schema:
            type: string
        - name: eye
          in: path
          required: true
          description: Eyeside of the patients LEFT or RIGHT
          schema:
            $ref: '#/components/schemas/EyeSide'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Examination'
      responses:
        '200':
          description: Return succes examination update message
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Return bad request message
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Return notFound message
          content:
            application/json:
              schema:
                type: string
    get:
      summary: Get examination by secNumber and eyeSide composite key.
      parameters:
        - name: secNumber
          in: path
          required: true
          description: The secNumber of the patient to return.
          schema:
            type: string
        - name: eye
          in: path
          required: true
          description: Eyeside of the patients LEFT or RIGHT
          schema:
            $ref: '#/components/schemas/EyeSide'
      responses:
        '200':
          description: Examination object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Examination'
        '400':
          description: Return bad request message
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Return not found message
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    PatientDetails:
      properties:
        secNumber:
          type: string
        name:
          type: string
        eyeColor:
          type: string
        hairColor:
          type: string
        birthDate:
          type: string
          format: datetime
      required:
        - secNumber
        - name
        - eyeColor
        - hairColor
        - birthDate
    Examination:
      properties:
        eyeAxis:
          type: number
        cylinder:
          type: number
        sphere:
          type: number
        patientId:
          type: integer
        eyeSide:
          $ref: '#/components/schemas/EyeSide'
    EyeSide:
      type: string
      enum: [ LEFT, RIGHT ]